---@tag lilvim
---@signature
---@text A modular and opinionated starting point for Neovim
---
--- MIT License Copyright (c) mvllow
---
--- ==============================================================================
---
--- Features:
---
--- - Self-contained modules
--- - Documented built-in functionality
--- - Deliciously simple to extend
---
--- Modules:
---
--- - |lil-complete|
--- - |lil-edit|
--- - |lil-lsp|
--- - |lil-places|
--- - |lil-quickfix|
--- - |lil-search|
--- - |lil-stats|
--- - |lil-subs|
--- - |lil-toggle|
--- - |lil-windows|
---
--- # Setup ~
---
--- When installed via a package manager, all modules can be required:
--- 	require('lil-<module>')
---
--- Each module is self-contained and can be individually copied to your own
--- configuration. Prefer the `plugin/` directory for automatic loading or the
--- `lua/` directory for more control.
---
--- # Documentation ~
---
--- Run `:helptags ALL` to regenerate help tags.
